//
//  EXPNode.h
//  ExpressionParser
//
//  Created by Jason Brennan on Aug-04-2013.
//  Copyright (c) 2013 Jason Brennan. All rights reserved.
//

#import <Foundation/Foundation.h>


/**
 Head node class for the little Abstract Syntax Tree generated by the parser.
*/
@interface EXPNode : NSObject <CPParseResult>


/**
 The numeric value of the node, if applicable.
*/
@property double value;

@end
